### ISSUE TITLE
Please compare to CleanLinks

### ISSUE THREAD

**Issue by wolftune** [idlewan/link_cleaner#4]
I'm guessing this is related to the WebExtension shift, but https://github.com/diegocr/cleanlinks is no longer shown at the Mozilla add-ons official pages although it's still working for me in FF ESR 52.

It has some nice options, whitelist capacity, does a yellow highlight to indicate when it cleans a link (which is nice in highlighting the problem of tracking links by making it obvious to users how common this stuff is). I'm not sure about details in comparison as I only just learned about Link Cleaner.

Since it looks like CleanLinks will be going away as a non-WebExtension, I would love to see (A) a published note about the differences for those migrating to Link Cleaner and (B) issues written up to add to Link Cleaner any desirable features from CleanLinks

Thanks!

**Comment by idlewan** [comment]
Link Cleaner works differently from CleanLinks: it doesn't inject javascript into every single page to change links. Instead, it listens on requests made to urls and change them to remove redirects or tracking.

I don't think I want the extension to add its own javascript to every page, which isn't good in terms of performance or memory consumption. That's why I doubt the "highlight links" is ever going to be ported from CleanLinks.

As it doesn't inject anything into pages, it doesn't pose any compatiblity problems with sites because it doesn't modify the content of the pages. A whitelist is thus not a useful feature.

All urls that are about to be visited are watched (for utm search parameters), in addition there is some site-specific filters.

I'm not sure I need to specify the differences to a dead addon, but if you've got suggestion on how to phrase it for the addon description, I'll read it. I'm unsure there is any desirable features that could be gained from CleanLInks, but I could be mistaken.

**Comment by wolftune** [comment]
Thanks for the detailed reply. I think the first thing would be, in my opinion, to add to the README or to an FAQ/manual/wiki something like "Unlike a plugin like the (outdated) CleanLinks, Link Cleaner doesn't inject JavaScript into pages to change links. Instead, it just listens to all url requests and changes them to remove redirects or tracking." Stuff like that is just good reference information for people trying to understand the plugin.

I accept that highlight-links won't be ported. I agree that performance and memory issues are a good thing to prioritize. To be clear though, CleanLinks only changes links upon clicking, I believe. But nevermind that, the point is to stop tracking, so whatever does that is great.

A whitelist is *potentially* useful if a redirect contains information that's actually necessary for something to operate. I'm not 100% this will ever come up. You could wait until there's a report of breakage. But I could imagine a case where a code included in a redirect is necessary for the operations of some service.

As a user myself, I mostly wanted to answer the question, "can I remove CleanLinks now and be just as free from tracking?"

Thanks!

**Comment by idlewan** [comment]
Thanks for the suggestion. I updated the description to include some more information, and re-organise it a little bit.

**Comment by hackel** [comment]
Heh, just for some perspective. I landed here specifically because of this addition to the description, comparing the addon to CleanLinks.  As a result, I'm now disappointed to see that much of the functionality is lacking.  Might want to explicitly differentiate yourself—seems like others are also complaining about a lack of CleanLinks features.
